dashpay/dashj

core/pom.xml
core/src/main/java/org/bitcoinj/core/PeerGroup.java
core/src/main/java/org/bitcoinj/core/TransactionBroadcast.java
core/src/main/java/org/bitcoinj/core/TransactionConfidence.java
core/src/main/java/org/bitcoinj/core/VersionMessage.java
core/src/main/java/org/bitcoinj/wallet/DefaultRiskAnalysis.java
core/src/main/java/org/bitcoinj/wallet/Protos.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
core/src/wallet.proto
examples/pom.xml
pom.xml
tools/pom.xml
wallettemplate/pom.xml

Modified TransactionConfidence to include:
Time
Number of connected peers
Minimum required connected peers
When a transaction is sent.  This information will be displayed using TransactionConfidence.toString.
A SENT TransactionConfidence.ChangeReason was added to signal that a transaction has been sent with Peer.sendMessage.  An app can use this information to signal the user that the transaction was sent.  Ideally the app should still wait for connected peers to announce the tx with "inv".  However in the case that only one peer is connected, then this SENT reason can be used to indicate some success to the user.
Additionally, after a transaction is locked (when using InstantSend), then the wallet is saved.

Transaction States

---

bls/src/main/cpp/dashj-bls-signature-wrapper.cpp

This was found to be missing from the Dash Wallet app as well.

BLS: Add missing delete method for AggregationInfoVector

---

core/src/main/java/org/bitcoinj/quorums/InstantSendManager.java
core/src/main/java/org/bitcoinj/quorums/SigningManager.java

InstantSendManager and SigningManager both have process pending methods
that were allocating memory when there was nothing to process.

LLMQBackgroundThread:  Reduce memory usage

---

core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java

Some exceptions were found to occur on some android versions that
resulted in crashes.  This will catch those.
This would also need to be `cherry-pick`ed into the release-0.16 branch if needed for 0.16.4

SimplifiedMasternodeListManager: Handle other exceptions when loading bootstrap

---

examples/src/main/java/org/bitcoinj/examples/BLSVerifySignature.java

This example program was supposed to show us a crash that happens in Full mode. Even after verifying over 2 million signatures, there were no crashes.

Add BLS Signature Verification example (DMD-1165)

---

core/src/main/java/org/bitcoinj/crypto/BLSLazyPublicKey.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListEntry.java
core/src/test/java/org/bitcoinj/crypto/BLSLazyPublicKeyTest.java
core/src/test/java/org/bitcoinj/evolution/SimplifiedMasternodesTest.java

The public keys are only used to verify quorums every 24 blocks.
A public key uses 152 bytes of native memory = about 0.7 MB for 5000 masternodes.
This memory is largely unused.  The idea behind lazy public keys is to store a public key only as the 48 bytes until it needs to be used to verify a quorum.  After that this implementation keeps the public key in memory as a BLSPublicKey (using java and native memory) and allows the 48 bytes to be freed up.
Perhaps a further optimization for reducing memory would be to always convert the 48 bytes to public keys each time the key is required, which is not often in SPV mode.

Use BLS Lazy Public keys on DMN Lists

---

core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChain.java
core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChainFactory.java
core/src/main/java/org/bitcoinj/wallet/Protos.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
core/src/main/proto/wallet.proto

This does not support BLS Key Chains.
This does not keep track of how many keys have been issued.  At first we only need one.  If the user wants to "reset" the blockchain user key, then this will not keep track of that.
Additionally, we don't have a standard scheme for that.  Would we use '1'th key instead of '0'?

Authentication Key Chains - Serialization / Deserialization

---

core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java
core/src/main/java/org/bitcoinj/crypto/KeyCrypterAESCBC.java
core/src/main/java/org/bitcoinj/crypto/KeyCrypterECDH.java
core/src/main/java/org/bitcoinj/crypto/Secp256k1ECDHAgreement.java
core/src/test/java/org/bitcoinj/crypto/KeyCrypterECDHTest.java
core/src/test/java/org/bitcoinj/wallet/FriendKeyChainTest.java

This PR will add support for the DashPay contactRequest encryptedPublicKey (plaintext) serialization format.  This format modifies the format of BIP32 and leaves out header, depth and child number.
Additionally, this PR aligns the ECDH implemention of DashSync with DashJ.

DeterministicKey: Add support for contact pub key (serialize, deserialize)

---

core/src/main/java/org/bitcoinj/wallet/Wallet.java

This fixes a bug that is in the CreateWallets example in android-dashpay.

Wallet: Specify type for each created authentication key chain

---

core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java

When a wallet is loaded from a file, outputs related to contact keys are not counted as spendable.
This will change the order of loading the wallet file so keys are loaded before processing wallet transactions and their unspent outpoints.

WalletProtobufSerializer: load all keys before processing transactions

---

core/src/main/java/org/bitcoinj/quorums/InstantSendManager.java

Fixing Android <= 6.0 issues that arise because of lambdas.
Instead of using `removeIf` I'm keeping keys that need to be deleted in a separate list and removing them in another loop.
Tested locally on Android API 22 emulator. Currently in QA.

[NMA-1006] Android 6.0 sync issues for 0.17

---

core/src/main/java/org/bitcoinj/crypto/BLSLazySignature.java

fix: prevent crash if lazy BLS signature is not initialized

---

core/src/main/java/org/bitcoinj/core/PeerGroup.java
core/src/main/java/org/bitcoinj/evolution/AbstractQuorumState.java
core/src/main/java/org/bitcoinj/evolution/MasternodeListSyncOptions.java
core/src/main/java/org/bitcoinj/evolution/QuorumRotationState.java
core/src/main/java/org/bitcoinj/evolution/QuorumState.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/main/java/org/bitcoinj/quorums/LLMQBackgroundThread.java
core/src/main/java/org/bitcoinj/quorums/SimplifiedQuorumList.java
examples/src/main/java/org/bitcoinj/examples/ForwardingService.java
examples/src/main/java/org/bitcoinj/examples/debug/BlockInfo.java
examples/src/main/java/org/bitcoinj/examples/debug/BlockReport.java
examples/src/main/java/org/bitcoinj/examples/debug/Report.java
examples/src/main/java/org/bitcoinj/examples/debug/TransactionReport.java

* handle case of loading inconsistant QuorumState (non-DIP24)
* refactor SimplifiedMasternodeListManager.SyncOptions to MasternodeListSyncOptions
* keep QuorumState synced with blockchain
* Prevent duplicate DIP24 quorum lists from being saved in memory
* check instantsend locks only if qrinfo is synced

fix: address many masternode/quorum sync issues

---

core/src/main/java/org/bitcoinj/crypto/KeyCrypterAESCBC.java
core/src/main/java/org/bitcoinj/wallet/Protos.java
core/src/main/proto/wallet.proto
core/src/test/java/org/bitcoinj/crypto/KeyCrypterAESCBCTest.java

* add a test that uses a EC private key for AES

feat: add EC and BLS key support to KeyCrypterAESCBC

---

core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChain.java

blockchain identity keys were not created as hardened key once they keychain was encrypted.

fix: modify constructor to create hardened children with identitykeychain

---

core/src/main/java/org/bitcoinj/crypto/bls/BLSDeterministicKey.java
core/src/main/java/org/bitcoinj/crypto/factory/BLSKeyFactory.java
core/src/main/java/org/bitcoinj/crypto/factory/ECKeyFactory.java
core/src/main/java/org/bitcoinj/crypto/factory/KeyFactory.java
core/src/main/java/org/bitcoinj/evolution/ProviderRegisterTx.java
core/src/main/java/org/bitcoinj/evolution/ProviderUpdateRegistarTx.java
core/src/main/java/org/bitcoinj/evolution/ProviderUpdateRevocationTx.java
core/src/main/java/org/bitcoinj/quorums/ChainLockSignature.java
core/src/main/java/org/bitcoinj/wallet/AbstractKeyChainGroupExtension.java
core/src/main/java/org/bitcoinj/wallet/AnyKeyChainGroup.java
core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChain.java
core/src/main/java/org/bitcoinj/wallet/KeyChainGroupExtension.java
core/src/main/java/org/bitcoinj/wallet/Protos.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
core/src/main/java/org/bitcoinj/wallet/authentication/AuthenticationGroupExtension.java
core/src/main/java/org/bitcoinj/wallet/authentication/AuthenticationKeyStatus.java
core/src/main/java/org/bitcoinj/wallet/authentication/AuthenticationKeyUsage.java
core/src/main/proto/wallet.proto
core/src/test/java/org/bitcoinj/evolution/ProviderTests.java
core/src/test/java/org/bitcoinj/quorums/ChainLockTest.java
core/src/test/java/org/bitcoinj/wallet/AbstractKeyChainGroupExtensionTest.java
core/src/test/java/org/bitcoinj/wallet/AllDeterministicKeyChainTest.java
core/src/test/java/org/bitcoinj/wallet/AnyDeterministicKeyChain2Test.java
core/src/test/java/org/bitcoinj/wallet/authentication/AuthenticationGroupExtensionExtensionTest.java
core/src/test/java/org/bitcoinj/wallet/authentication/AuthenticationKeyChainGroupTest.java
examples/src/main/java/org/bitcoinj/examples/RestoreFromSeedThenDump.java

This PR adds support for tracking masternode key usage during blockchain sync.
The AuthenticationGroupExtension is what does most of the work.  By default, this extension is not included in a Wallet object when created.
Future work: When we add EDDSA keys, we will refactor some of the extra duplicate classes away, hopefully.
Unit tests
hopefully none.

Feature core 19 masternode key bloomfilters

---

core/src/main/java/org/bitcoinj/core/NetworkParameters.java
core/src/main/java/org/bitcoinj/crypto/BLSLazyPublicKey.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeList.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListEntry.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/main/java/org/bitcoinj/params/MainNetParams.java
core/src/main/java/org/bitcoinj/params/TestNet3Params.java
core/src/main/java/org/bitcoinj/quorums/SimplifiedQuorumList.java
core/src/test/java/org/bitcoinj/evolution/SimplifiedMasternodeListEntryTest.java
core/src/test/java/org/bitcoinj/evolution/SimplifiedMasternodesTest.java

* allow BLSLazyPublicKey to serialize in different scheme
* applyDiff in SimplifiedMasternodeList will use scheme based on diff version
* serialize SimplifiedMasternodeListEntry according to version
* update SimplifiedMasternodesTest based on the above changes

fix: handle activation of Core 19/Basic Scheme

---

core/src/main/java/org/bitcoinj/evolution/ProviderUpdateServiceTx.java
core/src/test/java/org/bitcoinj/evolution/ProviderTests.java

Add the rest serialization support for version 2 of the ProviderUpdateServiceTx payload.

fix: update ProviderUpdateServiceTx to fully support BASIC_BLS_VERSION

---

.run/WalletTool Regular Empty.run.xml
core/src/main/java/org/bitcoinj/coinjoin/CoinJoin.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinClientManager.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinClientSession.java
core/src/main/java/org/bitcoinj/coinjoin/PendingDsaRequest.java
core/src/main/java/org/bitcoinj/coinjoin/PoolMessage.java
core/src/main/java/org/bitcoinj/coinjoin/PoolStatus.java
core/src/main/java/org/bitcoinj/coinjoin/listeners/CoinJoinTransactionListener.java
core/src/main/java/org/bitcoinj/coinjoin/listeners/CoinJoinTransactionType.java
core/src/main/java/org/bitcoinj/coinjoin/listeners/SessionCompleteListener.java
core/src/main/java/org/bitcoinj/coinjoin/progress/MixingProgressTracker.java
core/src/main/java/org/bitcoinj/coinjoin/utils/CoinJoinManager.java
core/src/main/java/org/bitcoinj/coinjoin/utils/CoinJoinReporter.java
core/src/main/java/org/bitcoinj/coinjoin/utils/MasternodeGroup.java
core/src/main/java/org/bitcoinj/coinjoin/utils/TransactionBuilder.java
core/src/main/java/org/bitcoinj/core/PeerGroup.java
core/src/main/java/org/bitcoinj/wallet/CoinJoinExtension.java
core/src/test/java/org/bitcoinj/coinjoin/TestWithMasternodeGroup.java
tools/src/main/java/org/bitcoinj/tools/WalletTool.java

feat(coinjoin): add tracking of transactions

---

core/src/main/java/org/bitcoinj/core/PeerGroup.java
core/src/main/java/org/bitcoinj/core/Transaction.java
core/src/main/java/org/bitcoinj/core/TransactionBroadcast.java
core/src/main/java/org/bitcoinj/core/TransactionConfidence.java

With Core 19, BIP61 was removed.  This feature would send messages back to DashJ telling it why a transaction was rejected, for instance.  This PR will simulate a BIP61 reject message internally so that DashJ clients can report some of these transaction errors to the users.
A workaround for Dash Core 0.14 was removed that would help us with sending transactions.  There was a problem with 0.14 where a DashJ client was being disconnected as soon as it connected.  This is a problem for DashJ clients, which may not be connected to the Dash Network at the time of sending a transaction.  In such a case, DashJ first makes connections and then would immediately send the TX.  However, the Dash Core 0.14 bug would kick DashJ clients off before sending could take place.  Our temp fix was to keep …

feat: track send errors

---

core/src/main/java/org/bitcoinj/coinjoin/CoinJoin.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinClientOptions.java
core/src/main/java/org/bitcoinj/coinjoin/Denomination.java
core/src/main/java/org/bitcoinj/coinjoin/UnmixedZeroConfCoinSelector.java
core/src/main/java/org/bitcoinj/coinjoin/utils/InputCoin.java
core/src/main/java/org/bitcoinj/coinjoin/utils/TransactionBuilder.java
core/src/main/java/org/bitcoinj/core/TransactionBag.java
core/src/main/java/org/bitcoinj/core/TransactionOutput.java
core/src/main/java/org/bitcoinj/wallet/CoinControl.java
core/src/main/java/org/bitcoinj/wallet/CoinJoinExtension.java
core/src/main/java/org/bitcoinj/wallet/SendRequest.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/java/org/bitcoinj/wallet/WalletEx.java
core/src/test/java/org/bitcoinj/coinjoin/CoinJoinCoinSelectorTest.java
core/src/test/java/org/bitcoinj/coinjoin/CoinJoinTest.java
core/src/test/java/org/bitcoinj/coinjoin/DenominatedCoinSelectorTest.java
core/src/test/java/org/bitcoinj/coinjoin/TestWithCoinJoinWallet.java
core/src/test/java/org/bitcoinj/coinjoin/UnmixedZeroConfCoinSelectorTest.java
core/src/test/java/org/bitcoinj/wallet/WalletTest.java
tools/src/main/java/org/bitcoinj/tools/WalletTool.java

* Fix CoinJoin Send - previously based on keys and denominated outputs
* Fix regular send
* Add some key, output info to the coinjoin wallet ext output

feat(coinjoin): fix private send and regular send

---

core/src/main/java/org/bitcoinj/core/TransactionBroadcast.java

If we are dropping peers after sending, then don't watch disconnects to detect errors in transactions.

fix: don't watch disconnects if dropping peers after broadcast

---

core/src/main/java/org/bitcoinj/core/Block.java
core/src/main/java/org/bitcoinj/evolution/AbstractQuorumState.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListEntry.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/test/java/org/bitcoinj/evolution/SimplifiedMasternodeListEntryTest.java

- [] I have added or updated relevant unit/integration/functional/e2e tests

fix: masternode list sync and block reward

---

core/src/main/java/org/bitcoinj/wallet/authentication/AuthenticationGroupExtension.java
core/src/test/java/org/bitcoinj/wallet/authentication/AuthenticationGroupExtensionTest.java

* separate reset and rescan functions
This should be resolved by not casting long time differences to int.
```
10:52:53 [main] CrashReporter - crashing because of uncaught exception
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.TimSort.mergeLo(TimSort.java:781) ~[na:0.0]
at java.util.TimSort.mergeAt(TimSort.java:518) ~[na:0.0]
at java.util.TimSort.mergeCollapse(TimSort.java:448) ~[na:0.0]
at java.util.TimSort.sort(TimSort.java:245) ~[na:0.0]
at java.util.Arrays.sort(Arrays.java:1263) ~[na:0.0]
at j$.util.List$-EL.sort(SourceFile:0) ~[na:0.0]
at org.bitcoinj.wallet.authentication.AuthenticationGroupExtension.reset(AuthenticationGroupExtension.java:893) ~[na:0.0]
```

fix: use Comparator that can handle long when sorting transactions

---

core/src/main/java/org/bitcoinj/coinjoin/CoinJoin.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinAccept.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinBaseManager.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinBaseSession.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinClientManager.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinClientQueueManager.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinClientSession.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinConstants.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinQueue.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinStatusUpdate.java
core/src/main/java/org/bitcoinj/coinjoin/utils/KeyHolderStorage.java
core/src/main/java/org/bitcoinj/coinjoin/utils/MasternodeGroup.java
core/src/main/java/org/bitcoinj/signers/CoinJoinTransactionSigner.java
core/src/main/java/org/bitcoinj/wallet/CoinJoinExtension.java
core/src/main/java/org/bitcoinj/wallet/WalletEx.java
core/src/test/java/org/bitcoinj/coinjoin/CoinJoinServer.java

Logging is reduced by marking some as "coinjoin-extra" which allows the client to ignore them and also by shortening some items such as proTxHashes to 16 characters (instead of 64).

fix: reduce logging

---

core/src/main/java/org/bitcoinj/evolution/QuorumState.java
core/src/main/java/org/bitcoinj/utils/Threading.java

Allow deadlock detection to be supported on Android.

feat: support deadlock detection on android

---

core/src/main/java/org/bitcoinj/masternode/owner/MasternodeConfig.java
core/src/main/java/org/bitcoinj/quorums/FinalCommitment.java
core/src/main/java/org/bitcoinj/quorums/GetQuorumRotationInfo.java
core/src/main/java/org/bitcoinj/quorums/InstantSendLock.java
core/src/main/java/org/bitcoinj/quorums/InstantSendManager.java
core/src/main/java/org/bitcoinj/quorums/LLMQBackgroundThread.java
core/src/main/java/org/bitcoinj/quorums/LLMQUtils.java
examples/src/main/java/org/bitcoinj/examples/debug/Report.java

* FinalCommitment, GetQuorumRotationInfo, InstantSend8, LLMQ*, MasternodeConfig, Report

style: clean up and simply code for several classes

---

core/src/main/java/org/bitcoinj/coinjoin/CoinJoinClientSession.java
core/src/main/java/org/bitcoinj/wallet/SendRequest.java

This PR has nothing to do with voting, but issues were found when when working on Username Voting related stories and as the iOS team was implementing coinjoin.

Feat voting

---

core/src/main/java/org/bitcoinj/core/AbstractManager.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeList.java
core/src/main/java/org/bitcoinj/quorums/ChainLocksHandler.java
core/src/main/java/org/bitcoinj/quorums/InstantSendManager.java
core/src/main/java/org/bitcoinj/wallet/CoinJoinExtension.java

fix: chainlock and islock issues

---

core/src/main/java/org/bitcoinj/evolution/QuorumState.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeList.java
core/src/main/java/org/bitcoinj/params/DevNetParams.java
core/src/main/java/org/bitcoinj/quorums/InstantSendManager.java
core/src/main/java/org/bitcoinj/quorums/SimplifiedQuorumList.java

fix: blocked mnlistdiff processing

---

core/src/main/java/org/bitcoinj/core/DualBlockChain.java
core/src/main/java/org/bitcoinj/evolution/QuorumState.java
core/src/main/java/org/bitcoinj/quorums/ChainLocksHandler.java
core/src/main/java/org/bitcoinj/quorums/SimplifiedQuorumList.java
core/src/main/java/org/bitcoinj/store/SPVDirectIOBlockStore.java
core/src/test/java/org/bitcoinj/store/SPVBlockStoreV2Test.java

Bugfix: sync stuck 33

---

core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/java/org/bitcoinj/wallet/listeners/WalletResetEventListener.java

feat: add WalletResetEventListener for wallet.reset()
