dashpay/dashj

pom.xml

Here you can find all the changes needed to deploy the release into Bintray

Configuring project for Bintray deployment

---

README.md
bls/README.md
bls/pom.xml
core/pom.xml
core/src/main/java/org/bitcoinj/core/Context.java
core/src/main/java/org/bitcoinj/core/InstantSend.java
core/src/main/java/org/bitcoinj/core/MasternodeSync.java
core/src/main/java/org/bitcoinj/core/NetworkParameters.java
core/src/main/java/org/bitcoinj/core/Transaction.java
core/src/main/java/org/bitcoinj/core/VersionMessage.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/main/java/org/bitcoinj/kits/FullPrunedWalletAppKit.java
core/src/main/java/org/bitcoinj/params/DevNetParams.java
core/src/main/java/org/bitcoinj/params/MainNetParams.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
examples/pom.xml
examples/src/main/java/org/bitcoinj/examples/DownloadBlockQuorumCommitment.java
examples/src/main/java/org/bitcoinj/examples/FullPrunedForwardingService.java
pom.xml
tools/pom.xml
wallettemplate/pom.xml

This will not allow connections to older nodes and will ensure that the correct chain is followed.
This also resolves memory leaks with MasternodeManager (by disabling obsolete message processing, by default) and other leaks that pertained to InstantSend.

DIP3 Activation Updates

---

core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java

This fix should help with Krip phones

Reduce max cache size

---

core/src/main/java/org/bitcoinj/core/Context.java
core/src/main/java/org/bitcoinj/core/TransactionBroadcast.java
core/src/main/java/org/bitcoinj/core/TransactionConfidence.java
core/src/main/java/org/bitcoinj/quorums/ChainLocksHandler.java
core/src/main/java/org/bitcoinj/quorums/InstantSendManager.java
core/src/main/java/org/bitcoinj/quorums/QuorumNotFoundException.java
core/src/main/java/org/bitcoinj/quorums/SigningManager.java
core/src/main/java/org/bitcoinj/wallet/Protos.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
core/src/main/proto/wallet.proto

See commits for what was changed.
This PR should be rebased and merge to preserve commit history.

Transaction History Status (NMA-20)

---

bls/src/main/cpp/dashj-bls-signature-wrapper.cpp
bls/src/main/java/org/dashj/bls/BLS.java
bls/src/main/java/org/dashj/bls/JNI.java
core/src/main/java/org/bitcoinj/crypto/BLSKeyExchangeCrypter.java
core/src/main/java/org/bitcoinj/crypto/BLSSecretKey.java
core/src/main/java/org/bitcoinj/wallet/Protos.java
core/src/main/proto/wallet.proto
core/src/test/java/org/bitcoinj/crypto/BLSExchangeKeyCrypterTest.java

Other changes may be required depending on if this lines up with the DashSync-iOS implementation.

Add BLS Integrated Encryption Scheme Support

---

core/src/main/java/org/bitcoinj/crypto/ChildNumber.java
core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java
core/src/main/java/org/bitcoinj/crypto/ExtendedChildNumber.java
core/src/main/java/org/bitcoinj/crypto/HDKeyDerivation.java
core/src/main/java/org/bitcoinj/evolution/EvolutionContact.java
core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChain.java
core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChainFactory.java
core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChainGroup.java
core/src/main/java/org/bitcoinj/wallet/DefaultKeyChainFactory.java
core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java
core/src/main/java/org/bitcoinj/wallet/ExternalKeyChain.java
core/src/main/java/org/bitcoinj/wallet/FriendKeyChain.java
core/src/main/java/org/bitcoinj/wallet/FriendKeyChainGroup.java
core/src/main/java/org/bitcoinj/wallet/KeyChainFactory.java
core/src/main/java/org/bitcoinj/wallet/KeyChainGroup.java
core/src/main/java/org/bitcoinj/wallet/Protos.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
core/src/main/proto/wallet.proto
core/src/test/java/org/bitcoinj/wallet/FriendKeyChainTest.java

Add Blockchain User Contact payment support

---

core/src/main/java/org/bitcoinj/core/ECKey.java
core/src/main/java/org/bitcoinj/crypto/BLSKeyExchangeCrypter.java
core/src/main/java/org/bitcoinj/crypto/KeyCrypterAESCBC.java
core/src/main/java/org/bitcoinj/crypto/KeyCrypterECDH.java
core/src/main/java/org/bitcoinj/wallet/FriendKeyChain.java
core/src/main/java/org/bitcoinj/wallet/Protos.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/proto/wallet.proto
core/src/test/java/org/bitcoinj/crypto/BLSExchangeKeyCrypterTest.java
core/src/test/java/org/bitcoinj/crypto/KeyCrypterECDHTest.java

This will be used by the DashPay library

Add ECDH KeyCrypter

---

core/src/main/java/org/bitcoinj/core/Peer.java
core/src/main/java/org/bitcoinj/core/SporkManager.java
core/src/main/java/org/bitcoinj/core/SporkMessage.java
core/src/test/java/org/bitcoinj/core/SporkMessageTest.java

Code Updates for LGTM (part 1)

---

core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChain.java
core/src/main/java/org/bitcoinj/wallet/DerivationPathFactory.java
core/src/main/java/org/bitcoinj/wallet/Protos.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
core/src/main/proto/wallet.proto

Chain Sync Improvements Phase 1

---

core/src/main/java/org/bitcoinj/uri/BitcoinURI.java
core/src/test/java/org/bitcoinj/uri/BitcoinURITest.java

Add support for the user field in BIP21 uri's.

BitcoinURI: Add user field

---

core/src/main/java/org/bitcoinj/core/Context.java
core/src/main/java/org/bitcoinj/core/Peer.java
core/src/main/java/org/bitcoinj/core/PeerGroup.java
core/src/main/java/org/bitcoinj/core/listeners/DownloadProgressTracker.java

NMA-620
Fix several issues:
1. Sync progress stops at 30% although the chain is already synced (stopped and restarted)
2. Run threads (llmq and masternodeSync) only when the PeerGroup is connected to the network

Sync and Thread Fixes

---

core/src/main/java/org/bitcoinj/core/Context.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/main/java/org/bitcoinj/params/DevNetParams.java
core/src/main/java/org/bitcoinj/params/RegTestParams.java
core/src/main/java/org/bitcoinj/quorums/LLMQParameters.java

Syncing was getting stuck at 30% (after headers) due to an invalid quorum type 101.
Type 101 (llmq_devnet) was added to the supported domain types.
Forwarding Service
App

Add LLMQ for Devnet Support

---

core/src/main/java/org/bitcoinj/core/Peer.java
core/src/main/java/org/bitcoinj/core/PeerGroup.java
core/src/main/java/org/bitcoinj/core/listeners/AbstractPeerDataEventListener.java
core/src/main/java/org/bitcoinj/core/listeners/DownloadProgressTracker.java
core/src/main/java/org/bitcoinj/core/listeners/PeerDataEventListener.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/main/java/org/bitcoinj/evolution/listeners/MasternodeListDownloadedListener.java
core/src/main/java/org/bitcoinj/kits/WalletAppKit.java
examples/src/main/java/org/bitcoinj/examples/ForwardingService.java

Need to track the status of the Masternode List sync stage and the PreBlockDownload stage.
MasternodeSync listener fields and methods were moved from the PeerGroup to Peer.

Smoother sync progress

---

core/src/main/java/org/bitcoinj/core/DarkSendPool.java
core/src/main/java/org/bitcoinj/evolution/EvolutionContact.java
core/src/main/java/org/bitcoinj/wallet/FriendKeyChain.java
core/src/main/java/org/bitcoinj/wallet/FriendKeyChainGroup.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/test/java/org/bitcoinj/wallet/FriendKeyChainTest.java

the accountReference will be used to distinguish multiple sets of addresses for a single contact

DashPay: Add support for accountReference

---

core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChain.java
core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChainGroup.java
core/src/main/java/org/bitcoinj/wallet/DerivationPathFactory.java
core/src/main/java/org/bitcoinj/wallet/Protos.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
core/src/main/proto/wallet.proto

Add invitations support, which is a type of credit funding transaction.

NMA-261: Add invitation support

---

.travis.yml
core/pom.xml
pom.xml

Dash Wallet failed to build due to missing dashj-bls dependency.  bls should be included in the SNAPSHOT version, though in the release builds it would not need to be.

Fix BLS build issues

---

core/src/main/java/com/hashengineering/crypto/X11.java
core/src/test/java/com/hashengineering/crypto/X11Test.java

The java X11 hash functions would interfere with each other if run at the same time in different threads.

Fix X11 race conditions and add tests

---

bls/pom.xml
core/pom.xml

Update two libraries for security purposes.

Security updates

---

core/src/main/java/org/bitcoinj/core/NetworkParameters.java
core/src/main/java/org/bitcoinj/core/Peer.java
core/src/main/java/org/bitcoinj/core/SporkManager.java
core/src/main/java/org/bitcoinj/quorums/LLMQUtils.java
core/src/main/java/org/bitcoinj/quorums/SigningManager.java

Core 0.17 Updates (NMA-883)

---

core/src/main/java/org/bitcoinj/core/BloomFilter.java
core/src/main/java/org/bitcoinj/params/PalinkaDevNetParams.java
core/src/main/java/org/bitcoinj/params/SchnappsDevNetParams.java
core/src/main/java/org/bitcoinj/quorums/Quorum.java
examples/src/main/java/org/bitcoinj/examples/ForwardingService.java

Support 0.20 Platform:
* Add schnapps network
* Add functions to BloomFilter and Quorum

DPP 0.20 Updates

---

core/src/main/java/org/bitcoinj/quorums/InstantSendManager.java

Fixing Android <= 6.0 issues that arise because of lambdas.
Instead of using `removeIf` I'm keeping keys that need to be deleted in a separate list and removing them in another loop.
Tested locally on Android API 22 emulator. Currently in QA.

[NMA-1006] Android 6.0 sync issues

---

core/src/main/java/org/bitcoinj/script/ScriptBuilder.java

Updates to support DPP 0.21

---

core/src/main/java/org/bitcoinj/core/Context.java
core/src/main/java/org/bitcoinj/core/MasternodeSync.java
core/src/main/java/org/bitcoinj/core/Peer.java
core/src/main/java/org/bitcoinj/core/PeerGroup.java
core/src/main/java/org/bitcoinj/core/listeners/AbstractPeerDataEventListener.java
core/src/main/java/org/bitcoinj/core/listeners/DownloadProgressTracker.java
core/src/main/java/org/bitcoinj/core/listeners/HeadersDownloadStartedEventListener.java
core/src/main/java/org/bitcoinj/core/listeners/HeadersDownloadedEventListener.java
core/src/main/java/org/bitcoinj/core/listeners/PeerDataEventListener.java
core/src/main/java/org/bitcoinj/core/listeners/PreBlocksDownloadListener.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/main/java/org/bitcoinj/evolution/listeners/MasternodeListDownloadedListener.java
core/src/main/java/org/bitcoinj/quorums/SimplifiedQuorumList.java

NMA-637: Add 0.18 headers first sync system to 0.17 (backport)

---

core/src/main/java/org/bitcoinj/core/NetworkParameters.java

Refactor some coin definition constants, document and deprecate (NMA-1078)

---

core/src/main/java/org/bitcoinj/core/NetworkParameters.java
core/src/main/java/org/bitcoinj/evolution/DeterministicMasternode.java
core/src/main/java/org/bitcoinj/evolution/DeterministicMasternodeState.java
core/src/main/java/org/bitcoinj/evolution/Masternode.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListEntry.java
core/src/main/java/org/bitcoinj/params/AbstractBitcoinNetParams.java
core/src/main/java/org/bitcoinj/params/DevNetParams.java

`supportsEvolution` is removed because it was no longer needed. This was to support DevNets when they were using an older version of Dash Core than Testnet and Mainnet.  This old version may have been Dash Core 0.15.
`supportsV18` is added to allow the client to interact with Dash Core 0.18 nodes as if this client was a 0.17 client.  By default, this value will be `true`.  But with DashPay, it will be set to `false` for now since Platform 0.21 does not support Core 0.18.

Allow lower protocol (NMA-1078)

---

core/src/main/java/org/bitcoinj/core/Context.java
core/src/main/java/org/bitcoinj/core/SporkManager.java
core/src/main/java/org/bitcoinj/core/listeners/DownloadProgressTracker.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java

Small Improvements for NMA-1078

---

core/src/main/java/org/bitcoinj/core/KeyId.java
core/src/main/java/org/bitcoinj/core/Utils.java
core/src/main/java/org/bitcoinj/evolution/GetSimplifiedMasternodeListDiff.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/main/java/org/bitcoinj/governance/GovernanceManager.java
core/src/main/java/org/bitcoinj/governance/GovernanceObject.java
core/src/main/java/org/bitcoinj/quorums/ChainLockSignature.java
core/src/main/java/org/bitcoinj/quorums/FinalCommitment.java
core/src/main/java/org/bitcoinj/quorums/SPVRecoveredSignaturesDatabase.java
core/src/main/java/org/bitcoinj/store/DatabaseFullPrunedBlockStore.java
core/src/main/java/org/bitcoinj/store/HashStore.java
examples/src/main/java/org/bitcoinj/examples/RestoreFromSeed.java
tools/src/main/java/org/bitcoinj/tools/BuildCheckpoints.java

This PR is to improve static code analysis at this site:
LGTM - https://lgtm.com/projects/g/dashevo/dashj/?mode=list

LGTM Improvements: Part 4 (NMA-1078)

---

core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java
core/src/main/java/org/bitcoinj/core/Peer.java
core/src/main/java/org/bitcoinj/core/Utils.java
core/src/main/java/org/bitcoinj/core/listeners/DownloadProgressTracker.java
core/src/main/java/org/bitcoinj/governance/GovernanceManager.java
core/src/main/java/org/bitcoinj/governance/GovernanceTriggerManager.java
core/src/main/java/org/bitcoinj/governance/GovernanceVote.java
core/src/main/java/org/bitcoinj/governance/Superblock.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java

Fixing Some things here:
https://lgtm.com/projects/g/dashevo/dashj/?mode=list

LGTM: Part 5

---

README.md

docs: Update README for gradle build system

---

.gitignore
core/src/main/java/org/bitcoinj/core/TransactionConfidence.java
core/src/main/java/org/bitcoinj/core/TxConfidenceTable.java
core/src/main/java/org/bitcoinj/params/KrupnikDevNetParams.java
core/src/main/java/org/bitcoinj/quorums/ChainLocksHandler.java
examples/src/main/java/org/bitcoinj/examples/ForwardingService.java
examples/src/main/java/org/bitcoinj/examples/ForwardingServiceEvo.java
tools/src/main/java/org/bitcoinj/tools/BuildCheckpoints.java
tools/src/main/java/org/bitcoinj/tools/NetworkEnum.java
tools/src/main/java/org/bitcoinj/tools/WalletTool.java

DPP 0.22 Updates

---

core/src/main/java/org/bitcoinj/core/VersionMessage.java
core/src/main/java/org/bitcoinj/params/KrupnikDevNetParams.java

* Update node list for Krupnik Devnet
* Format subVer properly

Dpp 0.22 part2

---

core/src/main/java/org/bitcoinj/core/Transaction.java
core/src/main/java/org/bitcoinj/script/Script.java
core/src/main/java/org/bitcoinj/wallet/DefaultRiskAnalysis.java
core/src/test/java/org/bitcoinj/wallet/DefaultRiskAnalysisTest.java

Dash Wallet should accept version 3 transactions immediately.

[NMA-1187] Version 3 Transactions Are Standard

---

contrib/README.md

docs: add contrib build instructions

---

core/src/main/java/com/hashengineering/crypto/X11.java
core/src/main/java/org/bitcoinj/core/MessageSigner.java
core/src/main/java/org/bitcoinj/core/UnsafeByteArrayOutputStream.java
core/src/main/java/org/bitcoinj/crypto/BLSId.java
core/src/main/java/org/bitcoinj/crypto/BLSPublicKey.java
core/src/main/java/org/bitcoinj/crypto/BLSSecretKey.java
core/src/main/java/org/bitcoinj/crypto/BLSSignature.java
core/src/test/java/org/bitcoinj/crypto/BLSExchangeKeyCrypterTest.java

style: remove C-Style arrays

---

core/src/main/java/org/bitcoinj/wallet/DeterministicKeyChain.java
core/src/test/java/org/bitcoinj/wallet/DeterministicKeyChainTest.java

The xpub of the account key will change after encryption.

Bugfix: xpub after encryption

---

core/build.gradle
core/src/main/java/org/bitcoinj/crypto/BLSPublicKey.java
core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChain.java
core/src/main/java/org/bitcoinj/wallet/DerivationPathFactory.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/java/org/bitcoinj/wallet/WalletProtobufSerializer.java
core/src/test/java/org/bitcoinj/wallet/DerivationPathFactoryTest.java
examples/src/main/java/org/bitcoinj/examples/ForwardingServiceEvo.java

Support DPP 0.23

---

core/build.gradle
core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java
core/src/main/java/org/bitcoinj/core/PeerGroup.java
core/src/main/java/org/bitcoinj/core/VersionMessage.java
core/src/main/java/org/bitcoinj/evolution/AbstractQuorumState.java
core/src/main/java/org/bitcoinj/evolution/QuorumRotationState.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/main/java/org/bitcoinj/params/MainNetParams.java
core/src/main/java/org/bitcoinj/params/TestNet3Params.java
core/src/test/java/org/bitcoinj/quorums/FinalCommitmentTest.java
examples/src/main/java/org/bitcoinj/examples/PortOpen.java
tools/src/main/java/org/bitcoinj/tools/WalletTool.java

fixes various problems related to quorum and masternode list synchronization.

fix: syncing quorums

---

core/src/main/java/org/bitcoinj/params/OuzoDevNetParams.java
examples/src/main/java/org/bitcoinj/examples/ForwardingService.java

feat: add ouzo devnet support

---

core/src/main/java/org/bitcoinj/params/BinTangDevNetParams.java

Add support for the BinTang devnet.

feat: support devnet-bintang

---

.github/workflows/tests.yml

tests: fix ci by using ubuntu-20.04 to avoid BLS errors

---

core/build.gradle
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinCoinSelector.java
core/src/main/java/org/bitcoinj/wallet/DefaultCoinSelector.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java

fix: coinjoin sending

---

core/src/main/java/org/bitcoinj/core/NetworkParameters.java
core/src/main/java/org/bitcoinj/evolution/QuorumRotationState.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeList.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListEntry.java
core/src/main/java/org/bitcoinj/params/TestNet3Params.java
core/src/main/java/org/bitcoinj/params/TwoIslandsDevNetParams.java
core/src/main/java/org/bitcoinj/params/WhiteRussianDevNetParams.java
core/src/main/java/org/bitcoinj/quorums/FinalCommitment.java
core/src/main/java/org/bitcoinj/quorums/SimplifiedQuorumList.java
examples/src/main/java/org/bitcoinj/examples/ForwardingService.java

fix: updates to support Core 19 RC7

---

core/src/main/java/org/bitcoinj/core/Peer.java
core/src/main/java/org/bitcoinj/core/PeerGroup.java
core/src/main/java/org/bitcoinj/evolution/AbstractQuorumState.java
core/src/main/java/org/bitcoinj/evolution/QuorumRotationState.java
core/src/main/java/org/bitcoinj/evolution/QuorumStateManager.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/main/java/org/bitcoinj/quorums/SimplifiedQuorumList.java
core/src/test/java/org/bitcoinj/evolution/QuorumRotationStateTest.java

fix: improve sync speed by making qrinfo process async

---

core/build.gradle
core/src/main/java/org/bitcoinj/core/NetworkParameters.java
core/src/main/java/org/bitcoinj/evolution/MasternodeListDiffException.java
core/src/main/java/org/bitcoinj/evolution/QuorumRotationState.java
core/src/main/java/org/bitcoinj/evolution/QuorumState.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeList.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/main/java/org/bitcoinj/params/AbsintheDevNetParams.java
core/src/main/java/org/bitcoinj/params/ScrewDriverDevNetParams.java
core/src/main/java/org/bitcoinj/quorums/SimplifiedQuorumList.java
examples/src/main/java/org/bitcoinj/examples/ForwardingService.java

fix: core 19 mnlistdiff scheme transition

---

core/src/main/java/org/bitcoinj/core/Coin.java
core/src/main/java/org/bitcoinj/quorums/InstantSendManager.java
core/src/test/java/org/bitcoinj/uri/BitcoinURITest.java

* Prevent NPE on LLMQ background thread
* Handle URI with amount that has more than 8 digits of precision

Bugfix release 19

---

core/build.gradle
core/src/main/java/org/bitcoinj/core/NetworkParameters.java
core/src/main/java/org/bitcoinj/core/VersionMessage.java
core/src/main/java/org/bitcoinj/evolution/AbstractQuorumState.java
core/src/main/java/org/bitcoinj/quorums/ChainLocksHandler.java

Release 19.0.1 Fixes

---

core/src/main/java/org/bitcoinj/evolution/AbstractQuorumState.java
core/src/main/java/org/bitcoinj/evolution/QuorumRotationState.java
core/src/main/java/org/bitcoinj/evolution/QuorumState.java
core/src/main/java/org/bitcoinj/evolution/SimplifiedMasternodeListManager.java
core/src/main/java/org/bitcoinj/params/MainNetParams.java
core/src/test/java/org/bitcoinj/core/VersionMessageTest.java

* MainNetParams: remove v19 activate height
* Verification Error crash fix - catch the exception and log it.

Bugfix v19 height crash

---

core/src/main/java/org/bitcoinj/wallet/AbstractKeyChainGroupExtension.java
core/src/main/java/org/bitcoinj/wallet/authentication/AuthenticationGroupExtension.java

Add some helper methods.
None.

feat: add coinjoin helpers

---

core/src/main/java/org/bitcoinj/wallet/AbstractKeyChainGroupExtension.java
core/src/main/java/org/bitcoinj/wallet/AuthenticationKeyChainGroup.java
core/src/main/java/org/bitcoinj/wallet/CoinJoinExtension.java
core/src/main/java/org/bitcoinj/wallet/Wallet.java
core/src/main/java/org/bitcoinj/wallet/authentication/AuthenticationGroupExtension.java
core/src/test/java/org/bitcoinj/evolution/QuorumStateValidateQuorumsTest.java
core/src/test/java/org/bitcoinj/quorums/QuorumRotationStateValidateQuorumsTest.java

fix: make getKeyChainType public

---

core/build.gradle
core/src/main/java/org/bitcoin/crawler/PeerSeedProtos.java
core/src/main/java/org/bitcoin/paymentchannel/Protos.java
core/src/main/java/org/bitcoin/protocols/payments/Protos.java
core/src/main/java/org/bitcoinj/protocols/channels/ClientState.java
core/src/main/java/org/bitcoinj/protocols/channels/ServerState.java
core/src/main/java/org/bitcoinj/wallet/Protos.java

Support building on M1 Mac or aarch64 systems.

chore: upgrade protobuf-javalite to 3.17 to support M1 CPU

---

core/src/main/java/org/bitcoinj/core/PeerGroup.java

fix bug when headerchain is empty and the blockchain has the genesis block

fix(core): stop at genesis block when copying to header chain

---

core/src/main/java/org/bitcoinj/evolution/AbstractQuorumState.java
core/src/main/java/org/bitcoinj/evolution/QuorumRotationState.java
core/src/main/java/org/bitcoinj/evolution/QuorumState.java
core/src/main/java/org/bitcoinj/quorums/InstantSendManager.java

fix: syncing issues and related crashes

---

core/src/main/java/org/bitcoinj/coinjoin/CoinJoinClientQueueManager.java
core/src/main/java/org/bitcoinj/coinjoin/CoinJoinClientSession.java
core/src/main/java/org/bitcoinj/wallet/CoinJoinExtension.java

feat(coinjoin): add mixing progress method to CoinJoinExtension

---

core/src/test/java/org/bitcoinj/coinjoin/CoinJoinClientOptionsTest.java
core/src/test/java/org/bitcoinj/coinjoin/CoinJoinEntryTest.java
core/src/test/java/org/bitcoinj/coinjoin/CoinJoinQueueTest.java
core/src/test/java/org/bitcoinj/coinjoin/CoinJoinSessionTest.java

tests: Add more coinjoin related tests

---

core/src/main/java/org/bitcoinj/coinjoin/CoinJoinClientSession.java

fix: align sorting of inputs by rounds to Dash Core (C++)

---

core/src/main/java/org/bitcoinj/wallet/CoinJoinExtension.java

Increase look ahead gap to 500 avoid missing transactions.

fix(coinjoin): change lookahead to 500
